name: learn-github-actions
on:
  push:
    branches: [main]
jobs:
  install-nodejs
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'
      - run: npm install 
      - run: npm run bats -v
      - run: node --version
